Benchain.FosilFreeFuture.Web/Controllers/CustomerController.cs
using System.Net;
using System.Text.Json;
using Benchain.FosilFreeFuture.Service.Models;
using Benchain.FosilFreeFuture.Web.Models;
using Benchain.FosilFreeFuture.Web.Models.DbEntities;
using Microsoft.AspNetCore.Mvc;
using Benchain.FosilFreeFuture.Web.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace Benchain.FosilFreeFuture.Web.Controllers;

public class CustomerController : Controller
{
  private readonly ILogger<CustomerController> _logger;
  private readonly MomentumContext _context;

  public CustomerController(ILogger<CustomerController> logger, MomentumContext context)
  {
    _logger = logger;
    _context = context;
  }

  public async Task<IActionResult> Index()
  {
    var model = new CustomerViewModel
    {
      ProfileCard = new ProfileCardModel{ CardTitle = "My profile", Profile = new ProfileModel()},
      FundedProjectCard = new ProjectsCardModel{CardTitle = "Funded projects", Projects = new List<ProjectModel>(), Type = "funded"},
      ActiveProjectCard = new ProjectsCardModel { CardTitle = "Active projects", Projects = new List<ProjectModel>(), Type = "active" }
    };
    var profileId = 1;
    var profile =  _context.ProfileDb.SingleOrDefault(p => p.Id == profileId);
    var profilesDb = await _context.ProfileDb.ToListAsync();
    var portfolios = await _context.PortfolioDb.ToListAsync();
    var batches = await _context.BadgeDb.ToListAsync();
    var projects = await _context.ProjectDb.ToListAsync();
    var approvedprojects = await _context.ApprovedProjectsDb.ToListAsync();
    var fundedprojects = await _context.FundedProjectDb.ToListAsync();

    model.ProfileCard.Profile = DbHelper.ParsProfileDb(profile);
    model.ProfileCard.Profile.Portfolio = new List<PortfolioModel>();
    model.ProfileCard.Profile.Badges = new List<BadgeModel>();

    model.FundedProjectCard.ProfileId = profileId.ToString();
    model.ActiveProjectCard.ProfileId = profileId.ToString();
    model.ProfileCard.ShowAddProfile = true;

    foreach (var portfoliodb in portfolios.Where(p=>p.ProfileId==profileId && p.Status==1))
    {
      model.ProfileCard.Profile.Portfolio.Add(DbHelper.ParsPortfolioDb(portfoliodb));

      foreach (var projectdb in projects)
      {
        var approved = approvedprojects.FirstOrDefault(a => a.ParticipantId == portfoliodb.ParticipantId && a.ProjectId == projectdb.Id);
        if (approved != null)
        {
          var funded = fundedprojects.FirstOrDefault(f =>
            f.ParticipantId == approved.ParticipantId && f.ProjectId == projectdb.Id && f.ProfileId == profile.Id);
          if (funded != null)
          {
            var projectmodel = DbHelper.ParseProjectDb(projectdb);
            projectmodel.Logo = profilesDb.FirstOrDefault(p => p.Id == approved.ParticipantId).Avatar.Remove(0, 5);
            ;
            projectmodel.ParticipantId = approved.ParticipantId;
            model.FundedProjectCard.Projects.Add(projectmodel);
          }
          else
          {
            var projectmodel = DbHelper.ParseProjectDb(projectdb);
            projectmodel.Logo = profilesDb.FirstOrDefault(p => p.Id == approved.ParticipantId).Avatar.Remove(0, 5);
            projectmodel.ParticipantId = approved.ParticipantId;
            model.ActiveProjectCard.Projects.Add(projectmodel);
          }
        }
      }
    }

    var denhaag = portfolios.Where(p => p.ParticipantId == 5 && p.Status==0);
    if (denhaag.Any())
    {
      model.ProfileCard.ShowHasMail = true;
    }

    foreach (var batchDb in batches.Where(p => p.ProfileId == profileId))
    {
      model.ProfileCard.Profile.Badges.Add(DbHelper.ParsBadgeDb(batchDb));
    }


    string json;

    //File from URL (in wwwroot) OR from API

    //ServicePointManager.Expect100Continue = true;
    //ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
    //json = (new WebClient()).DownloadString("https://localhost:7294/profile1.json");
    //model.ProfileCard = JsonSerializer.Deserialize<ProfileCardModel?>(json);
    
    //File from local files (in root project)
    //using (var r = new StreamReader("profile1.json"))
    //{
    //  json = r.ReadToEnd();
    //  model.ProfileCard = JsonSerializer.Deserialize<ProfileCardModel>(json);
    //}

    //using (var r = new StreamReader("fundedprojects.json"))
    //{
    //  json = r.ReadToEnd();
    //  model.FundedProjectCard = JsonSerializer.Deserialize<ProjectsCardModel>(json);
    //}

    //using (var r = new StreamReader("activeprojects.json"))
    //{
    //  json = r.ReadToEnd();
    //  model.ActiveProjectCard = JsonSerializer.Deserialize<ProjectsCardModel>(json);
    //}

    if (model.ProfileCard.Profile.Portfolio.Any())
    {
     model.ProfileCard.Profile.CurrentBalance = model.ProfileCard.Profile.Portfolio.Aggregate(0, (current, port) => current + port.Balance);
    }

    return View(model);
  }

  public IActionResult FundProject(int projectId, int profileId, string participantId)
  {

    var participant = 0;

    if (participantId != null)
    {
      participant = int.Parse(participantId);
    }

    var portfolio = _context.PortfolioDb.SingleOrDefault(p => p.ParticipantId == participant);
    if (portfolio == null) return RedirectToAction("Index", new { profileId });
    if(portfolio.Balance<10) return RedirectToAction("Index", new { profileId });

    portfolio.Balance -= 10; //FUND Project -10
    _context.Update(portfolio);
    _context.SaveChanges();
    
    var project = _context.ProjectDb.SingleOrDefault(p=>p.Id == projectId);
    if (project == null) return RedirectToAction("Index", new { profileId });
    project.FundsReceived += 10; //FUND Project
    _context.Update(project);
    _context.SaveChanges();
    


    var funded = _context.FundedProjectDb.SingleOrDefault(a => a.ParticipantId == participant  && a.ProjectId == projectId && a.ProfileId == profileId);
    if (funded == null)
    {
      funded = new FundedProjectDb
      {
        ParticipantId = participant,
        ProjectId = projectId,
        ProfileId = profileId

      };
      _context.FundedProjectDb.Add(funded);
      _context.SaveChanges();
    }

    return RedirectToAction("Index", new { profileId });

  }

}

Benchain.FosilFreeFuture.Web/Controllers/InitiatorController.cs
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using Benchain.FosilFreeFuture.Service.Interfaces;
using Benchain.FosilFreeFuture.Web.Models;
using Benchain.FosilFreeFuture.Web.ViewModels;
using Benchain.FosilFreeFuture.Service.Models;
using Benchain.FosilFreeFuture.Web.Models.DbEntities;
using Microsoft.EntityFrameworkCore;

namespace Benchain.FosilFreeFuture.Web.Controllers;

public class InitiatorController : Controller
{
  private readonly IProjectSmartContractService _projectSmartContract;
  private readonly ILogger<CustomerController> _logger;
  private readonly MomentumContext _context;

  public InitiatorController(IProjectSmartContractService projectSmartContract, ILogger<CustomerController> logger, MomentumContext context)
  {
    _projectSmartContract = projectSmartContract;
    _logger = logger;
    _context = context;
  }

  public async Task<IActionResult> Index(int? profileId, int? projectId)
  {
    profileId ??= 2;

    var projectModels = new List<ProjectModel>();
    var projectsOnBlockchainNetwork = _projectSmartContract.GetProjects();

    foreach (var project in projectsOnBlockchainNetwork)
    {
      var projectModel = new ProjectModel
      {
        Name = project.ProjectName,
        InitiatorWalletAddress = project.ProjectInitiated,
        Description = project.ProjectDescription,
        Country = project.ProjectCountry,
        FundsNeeded = (int)project.ProjectFundsNeeded,
        Image = project.ProjectImage,
        Status = project.ProjectStatus,
      };

      projectModels.Add(projectModel);
    }


    var model = new InitiatorViewModel()
    {
      ProfileCard = new ProfileCardModel
      {
        CardTitle = "Initiator profile",
        Profile = new ProfileModel()
      },
      FundedProjectCard = new ProjectsCardModel
      {
        CardTitle = "Your funded projects",
        Projects = new List<ProjectModel>(),
        Type = "closedproject"
      },
      ActiveProjectCard = new ProjectsCardModel
      {
        CardTitle = "Your active projects",
        Projects = new List<ProjectModel>(),
        Type = "openproject"
      },
      Project = new ProjectModel 
      { 
        Id = "1", 
        FundsNeeded = 0, 
        FundsReceived = 0 
      }
    };


    var profile = _context.ProfileDb.SingleOrDefault(p => p.Id == profileId);
    var projects = await _context.ProjectDb.ToListAsync();

    model.ProfileCard.Profile = DbHelper.ParsProfileDb(profile);
    model.ProfileCard.Profile.Portfolio = new List<PortfolioModel>();
    model.ProfileCard.Profile.Badges = new List<BadgeModel>();

    foreach (var projectdb in projects.Where(p => p.Initiated == "CO2OL" && p.Status == "closed"))
    {
      model.FundedProjectCard.Projects.Add(DbHelper.ParseProjectDb(projectdb));
    }

    foreach (var projectdb in projects.Where(p => p.Initiated == "CO2OL" && p.Status == "open"))
    {
      model.ActiveProjectCard.Projects.Add(DbHelper.ParseProjectDb(projectdb));
    }

    model.ActiveProjectCard.Projects.AddRange(projectModels);

    if (projectId != null)
    {
      var editProjectdb = _context.ProjectDb.SingleOrDefault(p => p.Id == projectId);
      model.Project = DbHelper.ParseProjectDb(editProjectdb);
    }

    return View(model);
  }

  public IActionResult CreateNewProject(ProjectModel projectModel)
  {
    _projectSmartContract.CreateProject(projectModel);

    return RedirectToAction("Index");
  }
}

Benchain.FosilFreeFuture.Web/Controllers/ParticipantController.cs
using System.Text.Json;
using Benchain.FosilFreeFuture.Service.Interfaces;
using Benchain.FosilFreeFuture.Service.Models;
using Benchain.FosilFreeFuture.Web.Models;
using Benchain.FosilFreeFuture.Web.Models.DbEntities;
using Benchain.FosilFreeFuture.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Benchain.FosilFreeFuture.Web.Controllers;

public class ParticipantController :Controller
{
  private readonly ILogger<CustomerController> _logger;
  private readonly MomentumContext _context;

  public ParticipantController(ILogger<CustomerController> logger, MomentumContext context)
  {
    _logger = logger;
    _context = context;
  }

  public async Task<IActionResult> Index(int? profileId)
  {
    profileId ??= 3;

    var model = new ParticipantViewModel()
    {
      ProfileCard = new ProfileCardModel { CardTitle = "Initiator profile", Profile = new ProfileModel() },
      FundedProjectCard = new ProjectsCardModel
        { CardTitle = "Approved projects", Projects = new List<ProjectModel>(), Type = "approved" },
      ActiveProjectCard = new ProjectsCardModel
        { CardTitle = "To approve projects", Projects = new List<ProjectModel>(), Type = "toapprove" }
     };
    
    var profile = _context.ProfileDb.SingleOrDefault(p => p.Id == profileId);
    var projects = await _context.ProjectDb.ToListAsync();
    var approvedprojects = await _context.ApprovedProjectsDb.ToListAsync();

    model.ProfileCard.Profile = DbHelper.ParsProfileDb(profile);
    model.ProfileCard.Profile.Portfolio = new List<PortfolioModel>();
    model.ProfileCard.Profile.Badges = new List<BadgeModel>();
    model.FundedProjectCard.ProfileId = profileId.ToString();
    model.ActiveProjectCard.ProfileId = profileId.ToString();

    foreach (var projectdb in projects)
    {
       var approved = approvedprojects.FirstOrDefault(a => a.ParticipantId == profile.Id && a.ProjectId == projectdb.Id);
       if (approved != null) model.FundedProjectCard.Projects.Add(DbHelper.ParseProjectDb(projectdb));
    }

    foreach (var projectdb in projects.Where(p => p.Status == "open"))
    {
      var approved = approvedprojects.FirstOrDefault(a => a.ParticipantId == profile.Id && a.ProjectId == projectdb.Id);
      if (approved == null) model.ActiveProjectCard.Projects.Add(DbHelper.ParseProjectDb(projectdb));
    }

    string json;

    //File from URL (in wwwroot) OR from API

    //ServicePointManager.Expect100Continue = true;
    //ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
    //json = (new WebClient()).DownloadString("https://localhost:7294/profile1.json");
    //model.ProfileCard = JsonSerializer.Deserialize<ProfileCardModel?>(json);


    //File from local files (in root project)
    //using (var r = new StreamReader("profile-klm.json"))
    //{
    //  json = r.ReadToEnd();
    //  model.ProfileCard = JsonSerializer.Deserialize<ProfileCardModel>(json);
    //}

    //using (var r = new StreamReader("approvedprojects.json"))
    //{
    //  json = r.ReadToEnd();
    //  model.FundedProjectCard = JsonSerializer.Deserialize<ProjectsCardModel>(json);
    //}

    //using (var r = new StreamReader("toapproveprojects.json"))
    //{
    //  json = r.ReadToEnd();
    //  model.ActiveProjectCard = JsonSerializer.Deserialize<ProjectsCardModel>(json);
    //}

    return View(model);
  }


  public IActionResult ApproveProject(int projectId, string profile)
  {
    var profileId = 0;

    if (profile != null)
    {
       profileId = int.Parse(profile);
    }

    var approved = _context.ApprovedProjectsDb.SingleOrDefault(a => a.ParticipantId == profileId && a.ProjectId == projectId);
    if (approved == null)
    {
      approved = new ApprovedProjectsDb
      {
        ParticipantId = profileId,
        ProjectId = projectId
      };
      _context.ApprovedProjectsDb.Add(approved);
      _context.SaveChanges();
    }

    return RedirectToAction("Index", new { profileId });

  }
}

Benchain.FosilFreeFuture.Web/Controllers/PortfolioController.cs
using Benchain.FosilFreeFuture.Service.Models;
using Benchain.FosilFreeFuture.Web.Models;
using Benchain.FosilFreeFuture.Web.Models.DbEntities;
using Benchain.FosilFreeFuture.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Benchain.FosilFreeFuture.Web.Controllers;

public class PortfolioController : Controller
{
  private readonly ILogger<CustomerController> _logger;
  private readonly MomentumContext _context;

  public PortfolioController(ILogger<CustomerController> logger, MomentumContext context)
  {
    _logger = logger;
    _context = context;
  }

  public async Task<IActionResult> Index()
  {
    var model = new CustomerViewModel
    {
      ProfileCard = new ProfileCardModel {CardTitle = "My profile", Profile = new ProfileModel()},
      FundedProjectCard = new ProjectsCardModel
        {CardTitle = "Funded projects", Projects = new List<ProjectModel>(), Type = "funded"},
      ActiveProjectCard = new ProjectsCardModel
        {CardTitle = "Active projects", Projects = new List<ProjectModel>(), Type = "active"}
    };
    var profileId = 1;
    var profile = _context.ProfileDb.SingleOrDefault(p => p.Id == profileId);
    var profilesDb = await _context.ProfileDb.ToListAsync();
    var portfolios = await _context.PortfolioDb.ToListAsync();
    var batches = await _context.BadgeDb.ToListAsync();
    var projects = await _context.ProjectDb.ToListAsync();
    var approvedprojects = await _context.ApprovedProjectsDb.ToListAsync();
    var fundedprojects = await _context.FundedProjectDb.ToListAsync();

    model.ProfileCard.Profile = DbHelper.ParsProfileDb(profile);
    model.ProfileCard.Profile.Portfolio = new List<PortfolioModel>();
    model.ProfileCard.Profile.Badges = new List<BadgeModel>();

    model.FundedProjectCard.ProfileId = profileId.ToString();
    model.ActiveProjectCard.ProfileId = profileId.ToString();
   

    foreach (var portfoliodb in portfolios.Where(p => p.ProfileId == profileId && p.Status == 1))
    {
      model.ProfileCard.Profile.Portfolio.Add(DbHelper.ParsPortfolioDb(portfoliodb));
    }

    foreach (var batchDb in batches.Where(p => p.ProfileId == profileId))
    {
      model.ProfileCard.Profile.Badges.Add(DbHelper.ParsBadgeDb(batchDb));
    }


    if (model.ProfileCard.Profile.Portfolio.Any())
    {
      model.ProfileCard.Profile.CurrentBalance = model.ProfileCard.Profile.Portfolio.Aggregate(0, (current, port) => current + port.Balance);
    }

    return View(model);
  }


  public IActionResult AddPortfolio(string code)
  {

    var portfolio = _context.PortfolioDb.SingleOrDefault(p => p.Id == 3);
    if (portfolio == null) return RedirectToAction("Index");

    portfolio.Status = 1; //Enable this portfolio Den haag
    _context.Update(portfolio);
    _context.SaveChanges();

    return RedirectToAction("Index", "Customer");

  }
  
}

Benchain.FosilFreeFuture.Web/Views/Shared/_AddPortfolio.cshtml
    <div class="col-12">
        <div class="card card-success">

            <div class="card-header">
                <h5 class="card-title font-weight-bolder">Add code</h5>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        @using (Html.BeginForm("AddPortfolio", "Portfolio", FormMethod.Post))
                        {
                            <div class="row">
                                <div class="col-2 col-form-label-lg">
                                    Code
                                </div>
                                <div class="col-2">
                                  <input style="text-transform:uppercase"  class="form-control" data-val="true" data-val-required="The Code field is required." id="code" name="code" type="text" value="">
                                </div>
                            </div>

                            <div class="row  m-2">
                                <div class="col-2 col-form-label-lg">
                                    <button  type="submit" class="btn btn-block bg-gradient-warning btn-lg" title="Connect your wallet to create a project">Add</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Benchain.FosilFreeFuture.Web/Views/Shared/_EditProject.cshtml
@model Benchain.FosilFreeFuture.Service.Models.ProjectModel;
<div class="row">
    <div class="col-12">
        <div class="card card-success">

            <div class="card-header">
                <h5 class="card-title font-weight-bolder">Start a new project</h5>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        @using (Html.BeginForm("CreateNewProject", "Initiator", FormMethod.Post))
                        {
                            @Html.HiddenFor(m => m.Id);
                            @Html.HiddenFor(m => m.FundsReceived);
                            @Html.HiddenFor(m => m.Status);
                            @Html.HiddenFor(m => m.ParticipantId);
                            @Html.HiddenFor(m => m.Logo);
                            <div class="row">
                                <div class="col-2 col-form-label-lg">
                                    Wallet Id
                                </div>
                                <div class="col-5">
                                    @Html.TextBoxFor(m => m.InitiatorWalletAddress, new {@class = "form-control", @id="participantWalletAddress", @disabled = true})
                                </div>
                                <div class="col-3">
                                    <button type="button" class="btn btn-block bg-gradient-warning btn-md" onclick="metaMaskButtonClick()">Connect your wallet (Web3)</button>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-2 col-form-label-lg">
                                    Choose project name
                                </div>
                                <div class="col-5">
                                    @Html.TextBoxFor(m => m.Name, new {@class = "form-control"})
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-2 col-form-label-lg">
                                    Choose project cost
                                </div>
                                <div class="col-5">
                                    @Html.TextBoxFor(m => m.FundsNeeded, new {@class = "form-control"})
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-2 col-form-label-lg">
                                    Choose project location country
                                </div>
                                <div class="col-5">
                                    @Html.TextBoxFor(m => m.Country, new {@class = "form-control"})
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-2 col-form-label-lg">
                                    Choose project description
                                </div>
                                <div class="col-5">
                                    @Html.TextBoxFor(m => m.Description, new {@class = "form-control"})
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-2 col-form-label-lg">
                                    Image
                                </div>
                                <div class="col-5">
                                    @Html.TextBoxFor(m => m.Image, new {@class = "form-control"})
                                </div>
                            </div>

                            <div class="row  m-2">
                                <div class="col-2 col-form-label-lg">
                                    <button id="btnCreateProject" disabled type="submit" class="btn btn-block bg-gradient-warning btn-lg" title="Connect your wallet to create a project">Save new project</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Benchain.FosilFreeFuture.Web/Views/Shared/_Navbar.cshtml
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="/" class="nav-link">Home</a>
      </li>
      @*  <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Projects A</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Projects B</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Projects C</a>
      </li>*@
    </ul>
  </nav>
  <!-- /.navbar -->

Benchain.FosilFreeFuture.Web/Views/Shared/_ProjectsCard.cshtml
@model ProjectsCardModel
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title font-weight-bolder">@Model.CardTitle</h5>
        <div class="card-tools">
          <button type="button" class="btn btn-tool" data-card-widget="collapse">
            <i class="fas fa-minus"></i>
          </button>
        </div>
      </div>
      <div class="card-body">
        <div class="row">
          @foreach (var project in Model.Projects)
          {
            <div class="col-4">

              <div class="card card-widget widget-user shadow-lg elevation-2">
                @if (project.IsDefault == 1)
                {
                  <div class="ribbon-wrapper">
                    <div class="ribbon bg-primary">
                      Default
                    </div>
                  </div>
                }
                <div class="widget-user-header text-white" style="background: url('../dist/img/project/@project.Image') center center;">
                  <h3 class="widget-user-username text-right font-weight-bolder">@project.Name&nbsp;&nbsp;&nbsp;</h3>
                  <h5 class="widget-user-desc text-right font-weight-bold">@project.Country&nbsp;&nbsp;&nbsp</h5>
                </div>
                @if (Model.Type == "funded" || Model.Type == "active")
                {
                  <div class="widget-user-logo">
                    <img class="img-logo elevation-2" src="../dist/img/logo/@project.Logo" alt="User Avatar">
                  </div>
                }
                <div class="card-footer">

                  <div class="row">
                    <div class="col-12 description-project">
                      
                        @project.Description
                      
                    </div>
                    <div class="col-12 pt-2">
                      Initiated by: @project.InitiatorWalletAddress
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-12 my-2">
                      <div class="progress-group">
                        <span class="progress-text font-weight-bold">Progress</span>
                        <span id="@project.Id-pt" class="float-right"><b>@project.PercentageFunded%</b>/ @project.FundsReceived Eth</span>
                        <div class="progress progress-md">
                          <div id="@project.Id-p" class="progress-bar bg-success rounded" style="width: @project.PercentageFunded%"></div>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div class="row my-2">
                    <div class="col-8">
                      @if (Model.Type == "funded")
                      {
                        <span class="text-center btn-block bg-gradient-secondary btn-lg">You funded 10 Eth</span>
                      }
                      @if (Model.Type == "active")
                      {
                        <a href="@Url.Action("FundProject","Customer", new {projectId=@project.Id, profileId=@Model.ProfileId, participantId=@project.ParticipantId })"class="btn btn-warning btn-lg">Backed</a>
                      }

                      @if (Model.Type == "approved")
                      {
                        <button type="button" class="btn btn-block bg-gradient-secondary btn-lg">Approved</button>
                      }
                      @if (Model.Type == "toapprove")
                      {
                        <a href="@Url.Action("ApproveProject","Participant", new {projectId=@project.Id, profile=@Model.ProfileId })"class="btn btn-warning btn-lg">Approve</a>
                      }

                      @if (Model.Type == "openproject")
                      {
                        <a href="@Url.Action("Index","Initiator", new {projectId=@project.Id })"class="btn btn-warning btn-lg">View project</a>
                      }
                      @if (Model.Type == "colsedproject")
                      {
                        <button type="button" class="btn btn-block bg-gradient-secondary btn-lg">View project</button>
                      }

                      @if (Model.Type == "project")
                      {
                        <button type="button" class="btn btn-block bg-gradient-secondary btn-lg">View project</button>
                      }
                      
                    </div>
                    <div class="col-4">
                      Funds needed:<br/>
                      <span class="font-weight-bolder">@project.FundsNeeded Eth</span>
                    </div>
                  </div>
                  
                </div>
              </div>
            </div>
          }
        </div>
      </div>
    </div>
  </div>
</div>